name: oam_iitk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - cmake
  - pyarrow
  - graphviz
  - rdkit
  - tensorflow
  - jupyter
  - ipywidgets
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - tsfresh
  - streamlit
  - gluonts
  - h5py
  - plotly
  - pip:
      - absl-py==1.4.0
      - alembic==1.15.1
      - altair==5.5.0
      - python-dotenv==1.0.1
      - pyngrok==7.2.3
prefix: /home/decision/anaconda3/envs/oam_iitk